# Generated by Django 3.2.3 on 2021-07-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut colaborador')),
                ('fotop', models.ImageField(upload_to='img', verbose_name='foto perfil')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre completo')),
                ('celular', models.IntegerField(verbose_name='celular')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('correo', models.CharField(max_length=100, verbose_name='correo electronico')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('contraseña', models.CharField(max_length=15, verbose_name='contraseña')),
            ],
        ),
    ]
