# Generated by Django 3.2.3 on 2021-07-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_colaborador_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fotop',
            field=models.ImageField(upload_to='img/', verbose_name='foto perfil'),
        ),
    ]
